# Generated by Django 2.2.24 on 2021-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_field', models.CharField(help_text='Help Text1 by Mark', max_length=200)),
                ('add_field', models.CharField(help_text='Help Text2 by Mark', max_length=200)),
            ],
            options={
                'ordering': ['main_field'],
            },
        ),
    ]
