# Generated by Django 2.2.24 on 2021-07-14 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testable',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Model Representaion Name', max_length=200),
            preserve_default=False,
        ),
    ]
