# Generated by Django 2.2.24 on 2021-07-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testable_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testable',
            options={'ordering': ['name']},
        ),
    ]
