# Generated by Django 2.2.24 on 2021-07-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210714_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testable',
            name='add_field',
            field=models.CharField(default='additional_name_', help_text='Help Text2 by Mark', max_length=200),
        ),
        migrations.AlterField(
            model_name='testable',
            name='main_field',
            field=models.CharField(default='main_name_', help_text='Help Text1 by Mark', max_length=200),
        ),
    ]
