# Generated by Django 2.2.24 on 2021-07-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210714_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testable',
            new_name='Note',
        ),
    ]
