# Generated by Django 2.2.24 on 2021-07-14 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210714_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Note')),
            ],
        ),
    ]
