# Generated by Django 2.2.24 on 2021-07-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_book_bookinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
