# Generated by Django 2.2.24 on 2021-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210714_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['token'],
            },
        ),
    ]
