# Generated by Django 2.2.24 on 2021-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_registertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertoken',
            name='token',
            field=models.CharField(max_length=6),
        ),
    ]
