# Generated by Django 2.2.24 on 2021-08-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210807_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registertoken',
            options={},
        ),
    ]
