# Generated by Django 3.2.6 on 2021-09-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210914_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
