# Generated by Django 3.2.6 on 2021-10-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
